### ISSUE TITLE
Console spam for NullPointer

### ISSUE THREAD

**Issue by CodingAir** [CodingAir/TradeSystem#222]
```
19.09 19:38:13 [Server] INFO java.lang.NullPointerException: null
19.09 19:38:13 [Server] WARN [TradeSystem] Task #636 for TradeSystem v1.2.1 generated an exception
19.09 19:38:13 [Server] INFO java.lang.NullPointerException: null
19.09 19:38:13 [Server] WARN [TradeSystem] Task #636 for TradeSystem v1.2.1 generated an exception
19.09 19:38:13 [Server] INFO java.lang.NullPointerException: null
19.09 19:38:13 [Server] WARN [TradeSystem] Task #636 for TradeSystem v1.2.1 generated an exception
19.09 19:38:13 [Server] INFO java.lang.NullPointerException: null
19.09 19:38:13 [Server] WARN [TradeSystem] Task #636 for TradeSystem v1.2.1 generated an exception
19.09 19:38:13 [Server] INFO java.lang.NullPointerException: null
19.09 19:38:13 [Server] WARN [TradeSystem] Task #636 for TradeSystem v1.2.1 generated an exception
19.09 19:38:13 [Server] INFO java.lang.NullPointerException: null
19.09 19:38:13 [Server] WARN [TradeSystem] Task #636 for TradeSystem v1.2.1 generated an exception
19.09 19:38:13 [Server] INFO java.lang.NullPointerException: null
19.09 19:38:13 [Server] WARN [TradeSystem] Task #636 for TradeSystem v1.2.1 generated an exception
19.09 19:38:13 [Server] INFO java.lang.NullPointerException: null
19.09 19:38:13 [Server] WARN [TradeSystem] Task #636 for TradeSystem v1.2.1 generated an exception
19.09 19:38:13 [Server] INFO java.lang.NullPointerException: null
```

```yaml
TradeSystem:
  Prefix: '&8[&cTrade&8] &r'
  Language: ENG
  #Permissions:
  #   "tradesystem.trade": Can accept/deny/toggle trade requests
  #   "tradesystem.trade.initiate": Can invite players for trades
  #If permissions are disabled, every player is able to accept/deny/toggle/initiate trades
  Permissions: false

  # Both traders have to add an item/money to finish the trade
  Trade_Both: true
  Trade_with_money: true
  #Values: Vault, Essentials, Exp
  Economy_priority:
  - Vault
  - Essentials
  - Exp
  Trade_Distance:
    enabled: true
    distance_in_blocks: 50
  Allowed_GameModes:
  - SURVIVAL
  Blocked_Worlds:
  - ExampleWorld-1
  - ExampleWorld-2
  Blacklist:
  - '{"Material":"AIR","Data":0}'
  - '{"Displayname":"&cExample","Material":"AIR","Data":0}'
  - '{"Displayname":"&cExample, which blocks all items with this strange name!"}'

  Trade_Countdown:
    Enabled: true
    #in ticks (20 ticks = 1 second)
    Interval: 20
    Repetitions: 3

  # true: After finishing a trade all overflowing items will be dropped, if the inventory is full
  # false: Prevent the trade partner to put too much items into the gui
  Trade_Drop_Items: true

  # After 60 seconds the request will be expired
  Request_Cooldown_In_Sek: 60

  Action_To_Cancel:
    Player_get_damaged: true

  Action_To_Request:
    Shift_Rightclick: false

  Easy_Money_Selection:
    Enabled: true
    #Do NOT use special symbols (e.g. '$') here.
    #Use characters only!
    Shortcuts:
    - Keys:
      - k
      Value: 1000
    - Keys:
      - m
      - mio
      Value: 1000000

  # Sound names can be found here: https://github.com/CodingAir/CodingAPI/tree/master/src/main/java/de/codingair/codingapi/server/sounds/Sound.java
  Sounds:
    Trade_Started:
      Name: LEVEL_UP
      Volume: 0.6
      Pitch: 1.0
    Trade_Finished:
      Name: LEVEL_UP
      Volume: 0.6
      Pitch: 1.0
    Trade_Blocked:
      Name: NOTE_BASS
      Volume: 0.8
      Pitch: 0.6
    Trade_Cancelled:
      Name: ITEM_BREAK
      Volume: 0.6
      Pitch: 1.0
    Trade_Request:
      Name: ORB_PICKUP
      Volume: 0.6
      Pitch: 1.0
    Countdown_Tick:
      Name: ORB_PICKUP
      Volume: 0.6
      Pitch: 1.0
    Countdown_Stop:
      Name: ITEM_BREAK
      Volume: 0.6
      Pitch: 1.0
```
